### ISSUE TITLE
Request for weights

### ISSUE THREAD

**Issue by potpov** [pengfeiliHEU/M2I2#2]
Hello, 

Thank you for your work! Could you also upload the weights of your final pre-trained model? 
the ones you refer as _med_pretrain_29.pth_ in the readme. 

NOTE: CLEF22 is not available anymore since the challenge is complete. It is not possible to easily replicate your experiments.

**Comment by pengfeiliHEU** [comment]
Sure, you can access it at https://pan.baidu.com/s/11RSXOfHV-EX8EyKF006qog using the code '4blx'. Afterwards, we welcome you to follow our work (https://github.com/pengfeiliHEU/MUMC) that will be presented at MICCAI 2023 this year.

**Comment by potpov** [comment]
Thanks a lot and congrats for your publication!
