### ISSUE TITLE
How to generate the answer_list.json files of VQA task?

### ISSUE THREAD

**Issue by lycutter** [pengfeiliHEU/M2I2#3]
Hello, Thanks for sharing the code. Could you please provide the answer_list.json file or its generated code? Looking forward to your reply.

**Comment by pengfeiliHEU** [comment]
You can put all the answers into a list and then remove duplicate answers. Finally, save the final answers to a JSON file.

**Comment by rhyhck** [comment]
> You can put all the answers into a list and then remove duplicate answers. Finally, save the final answers to a JSON file.

Hello, can you be more specific about the format of the answer_ Iist? Is this a two-dimensional or one-dimensional list? Are the elements in dictionary form?

**Comment by deng1604** [comment]
> > 您可以将所有答案放入一个列表中，然后删除重复的答案。最后，将最终答案保存到 JSON 文件中。
> 
> 您好，您能更具体地介绍一下 answer_ Iist 的格式吗？这是二维列表还是一维列表？元素是字典形式吗？

你好，你可以看下这个链接：
https://github.com/pengfeiliHEU/M2I2/issues/8
