### ISSUE TITLE
Could you provide the pre-trained or trained models' weights

### ISSUE THREAD

**Issue by GaryGuTC** [pengfeiliHEU/M2I2#4]
Hi:
Thanks so much for your work and code sharing. Could you update the pre-trained model weights or the dataset of Imageclef2022 medical? That will be much helpful for me. The dataset is hard to get because the ImageCLEF Caption 2022 has been finished. 

Best regards

**Comment by pengfeiliHEU** [comment]
Sure, you can access it at https://pan.baidu.com/s/11RSXOfHV-EX8EyKF006qog using the code '4blx'. Afterwards, we welcome you to follow our work (https://github.com/pengfeiliHEU/MUMC) that will be presented at MICCAI 2023 this year.

**Comment by GaryGuTC** [comment]
Thanks so much for your help !
