### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by pengyuheng-github** [pengfeiliHEU/M2I2#5]
Hello! Thank you for your work. As a beginner, I want to learn your results. So can you share the four datasets you are using in your project? I didn't find all datasets on the web, especially pre-trained datasets.

**Comment by highwang** [comment]
> Hello! Thank you for your work. As a beginner, I want to learn your results. So can you share the four datasets you are using in your project? I didn't find all datasets on the web, especially pre-trained datasets.

Hello！Have you found the dataset yet? I am also looking for a dataset, especially pre-trained datasets.

**Comment by pengfeiliHEU** [comment]
Hello, thank you for your interest in this work. If you cannot find the relevant dataset online, you can contact the authors of the dataset-related literature via email to request it. Best of luck!

> > Hello! Thank you for your work. As a beginner, I want to learn your results. So can you share the four datasets you are using in your project? I didn't find all datasets on the web, especially pre-trained datasets.
> 
> Hello！Have you found the dataset yet? I am also looking for a dataset, especially pre-trained datasets.

Hello, thank you for your interest in this work. If you cannot find the relevant dataset online, you can contact the authors of the dataset-related literature via email to request it. Best of luck!

**Comment by ZuoZicheng** [comment]
> > Hello! Thank you for your work. As a beginner, I want to learn your results. So can you share the four datasets you are using in your project? I didn't find all datasets on the web, especially pre-trained datasets.
> 
> Hello！Have you found the dataset yet? I am also looking for a dataset, especially pre-trained datasets.

+1, I have encountered the same problem as you, have you solved it so far ?
