### ISSUE TITLE
about the comparasion

### ISSUE THREAD

**Issue by rhyhck** [pengfeiliHEU/M2I2#6]
Hi, How do you reproduce CMSA-MPTP?

**Comment by pengfeiliHEU** [comment]
I have replicated the CMSA code, and the results are 1-2 % lower than those presented in the paper. However, the results I cited in my paper are those presented by the authors in their paper.

**Comment by rhyhck** [comment]
> I have replicated the CMSA code, and the results are 1-2 % lower than those presented in the paper. However, the results I cited in my paper are those presented by the authors in their paper.

Hello, I have also reproduced the code for CMSA-MPTP, but the open acc is 20% lower than the paper result, and the all acc is 10% lower than the paper result. Could you please let me know what changes you need to make during the reproduction process? I didn't modify any parameters, but the results were vastly different, thanks!

**Comment by pengfeiliHEU** [comment]
> > I have replicated the CMSA code, and the results are 1-2 % lower than those presented in the paper. However, the results I cited in my paper are those presented by the authors in their paper.
> 
> Hello, I have also reproduced the code for CMSA-MPTP, but the open acc is 20% lower than the paper result, and the all acc is 10% lower than the paper result. Could you please let me know what changes you need to make during the reproduction process? I didn't modify any parameters, but the results were vastly different, thanks!


Hello, you need to load the model weights made available by the author for validation.

**Comment by rhyhck** [comment]
> > > I have replicated the CMSA code, and the results are 1-2 % lower than those presented in the paper. However, the results I cited in my paper are those presented by the authors in their paper.
> > 
> > 
> > Hello, I have also reproduced the code for CMSA-MPTP, but the open acc is 20% lower than the paper result, and the all acc is 10% lower than the paper result. Could you please let me know what changes you need to make during the reproduction process? I didn't modify any parameters, but the results were vastly different, thanks!
> 
> Hello, you need to load the model weights made available by the author for validation.

ok，I get it ,thanks!
