### ISSUE TITLE
Can you provide us with the division of the data set? How to reproduce the results of the paper

### ISSUE THREAD

**Issue by languandong** [pengfeiliHEU/M2I2#7]
If you want to reproduce the results of the paper, can you open source the code for dividing and processing the data set?
Thank you very much

**Comment by pengfeiliHEU** [comment]
Our dataset division is consistent with previous works, such as MEVF, MMQ, M3AE, where the majority of methods adopted the same dataset partitioning approach, without arbitrary divisions.
