### ISSUE TITLE
Can I confirm with you the process of generating answer_list ?

### ISSUE THREAD

**Issue by languandong** [pengfeiliHEU/M2I2#8]
Maybe I guess：
1. Read train set files and test set files
2. Add together the labels of these two files
3. Convert all uppercase to lowercase
4. Remove duplicate labels，output as answer_list 

Do I guess this process correctly?

**Comment by pengfeiliHEU** [comment]
Yes. My answer_list.json file below.
[answer_list.json](https://github.com/pengfeiliHEU/M2I2/files/13512364/answer_list.json)

**Comment by languandong** [comment]
> Yes. My answer_list.json file below. [answer_list.json](https://github.com/pengfeiliHEU/M2I2/files/13512364/answer_list.json)

Thank you very much!

**Comment by deng1604** [comment]
> > 是的。我的 answer_list.json 文件在下面。[answer_list.json](https://github.com/pengfeiliHEU/M2I2/files/13512364/answer_list.json)
> 
> 谢谢！

请问，有这个文件吗？
answer_trainval_list.json

**Comment by deng1604** [comment]
另外，请问下这个 answer_list.json 文件是对应哪个数据集的呢

**Comment by wangpengyu-debug** [comment]
> Yes. My answer_list.json file below. [answer_list.json](https://github.com/pengfeiliHEU/M2I2/files/13512364/answer_list.json)

Is this the answer list for VQA_RAD or Slake?
